### ISSUE TITLE
Nvidia Shield TV/crashing

### ISSUE THREAD

**Issue by Blurayx** [tamland/xbmc-addon-watchdog#11]
watchdog works great but when I exit kodi. NSTV shows an error saying "unfortunately kodi has stopped"
this only happens when poll reclusively is enabled.

**Comment by tamland** [comment]
Need more information, such as a debug log. How to obtain one is explained in http://forum.kodi.tv/showthread.php?tid=128896 For unconfirmed issue/support it's better if you post in the forum thread.
