### ISSUE TITLE
Delay after reboot

### ISSUE THREAD

**Issue by niro1987** [tamland/xbmc-addon-watchdog#5]
I'm manually mounting my network shares in a new folder /shares/Movies and /shares/Series. After every reboot watchdog gives me the error that the folder locations for movies and tv-shows do not exist. Is it possible to add DELAY_AFTER_BOOT (in seconds) to the configuration (upon next update or so).

P.S. Great work! You make all the XBMC user lives much better!

**Comment by tamland** [comment]
added, some time ago, as 'startup delay'
