### ISSUE TITLE
Speed issues with watchdog & video addons

### ISSUE THREAD

**Issue by Mazo** [tamland/xbmc-addon-watchdog#9]
Using a Raspberry Pi (v1) with either 256MB or 512MB of RAM with the Watchdog addon enabled causes incredibly long delays when browsing through video addons such as Twitch.TV or YouTube. (Minutes per page!)

Disabling Watchdog immediately restores both addons to full speed with data loading almost instantly. Could Watchdog be trigging false positives repeatedly as data is loaded from these addons bringing the whole system to a grinding halt?

**Comment by tamland** [comment]
Known issue, which happens when network/server is slow or unresponsive. Should be fixed with xbmc/xbmc#6869 in kodi 15 beta 1.
